apiVersion: 1

datasources:
  - name: InfluxDB-TwinData
    uid: influxdb_twin
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: digitaltwin
      defaultBucket: twin_data
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    isDefault: true
    editable: true
